services:
  postgres:
    image: postgres:16-alpine
    container_name: challenge-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgresdata:/var/lib/postgresql/data

  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    container_name: challenge-dragonfly
    ulimits:
      memlock: -1
    ports:
      - ${DRAGONFLY_PORT}:${DRAGONFLY_PORT}
    restart: unless-stopped
    volumes:
      - dragonflydata:/data

volumes:
  postgresdata:
  dragonflydata:
