services:
  postgres:
    image: postgres:16-alpine
    container_name: challenge-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgresdata:/var/lib/postgresql/data

  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    container_name: challenge-dragonfly
    ulimits:
      memlock: -1
    ports:
      - ${DRAGONFLY_PORT}:${DRAGONFLY_PORT}
    restart: unless-stopped
    volumes:
      - dragonflydata:/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_USER: ${POSTGRES_USER}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      ADMINER_DEFAULT_TYPE: postgresql
      ADMINER_DEFAULT_PORT: 5432
      ADMINER_DEFAULT_DB: ${POSTGRES_DATABASE}

volumes:
  postgresdata:
  dragonflydata:
